サインアップ機能
shinonome-inc/backend-final-assignment-Y-Yoshihiro-Kaneko pull request #1
Opened 2024-10-14 18:44 UTC by YO-RO

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/preview)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] 作成したモデルを全てDjango管理画面に登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2024-10-23 05:30 UTC, taku072002T commented
その他、機能的に不十分な箇所は見られないと思います！
これらを修正していただき次第、１次レビューOKとさせていただきます！

2024-10-23 07:56 UTC, taku072002T requested changes
こちら、修正箇所になります！

2024-10-23 08:52 UTC, YO-RO commented on accounts/forms.py
> +    class Meta(UserCreationForm.Meta):
[ドキュメント](https://docs.djangoproject.com/ja/4.2/topics/db/models/#meta-inheritance) によると `Meta` クラスの継承はされないです。また、実際に試してみるとユーザー名の `input` タグの `autocomplete` 属性などが消えていて継承されていないことを確認しました。

2024-10-23 09:15 UTC, taku072002T commented on accounts/forms.py
> +    class Meta(UserCreationForm.Meta):
了解しました。
私も、勉強不足かと思いドキュメントを見直してみました。
DjangoAPIドキュメントBaseUserCreationForm項を見返したところ、Metaクラスが定義されていて、それは現コードまで継承されているものだと思っていたのですが...fieldclassがリセットされているということは、実際に継承されていないということでしょうか。
こちら、機能的には問題が見受けられないので、二次レビューにて、指摘をいただかなかった場合無視していただいて結構です。

2024-10-23 09:26 UTC, YO-RO commented on accounts/forms.py
> +    class Meta(UserCreationForm.Meta):
了解です。レビューありがとうございました！

2024-10-23 09:26 UTC, taku072002T commented on accounts/forms.py
> +    class Meta(UserCreationForm.Meta):
追記です。
そも、基底クラスは抽象クラスでないというのもあり、Metaがデフォで継承されることはないと言いますね。
なるほどです。

2024-10-23 09:27 UTC, taku072002T commented
こちら、一次レビューOKになります！

2024-10-23 13:06 UTC, YO-RO commented
了解です！レビューありがとうございました！

2024-10-25 03:31 UTC, gw31415 commented on accounts/forms.py
> +    class Meta(UserCreationForm.Meta):
確認しました！大丈夫です！

2024-10-25 03:32 UTC, gw31415 commented
LGTM！
セルフマージして次の課題に進んでください！

2024-10-27 12:44 UTC, merged